### ISSUE TITLE
[BUG] It closes itself too frequent

### ISSUE THREAD

**Issue by ghost** [JiPaix/Fukayo#751]
**Describe the bug**
Fukayo suddenly shuts itself down
**To Reproduce**
It happens randomly, sometimes docker-compose down and docker-compose up -d works but it does not work right now it gives '[18:0406/142338.230344:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory'

**Expected behavior**
Do not shutdown the if I did not stop the docker container

**Additional context**
Fukayo version 0.19.28 Running on Ubuntu 22.04
**Docker Compose**
```version: "3.8"
services:
  fukayo:
    image: jipaix/fukayo:beta
    container_name: fukayo
    ports:
      - "4444:4444"
    user: "1000:1000"
    volumes:
      - type: bind
        source: /home/toprak/fukayo
        target: /home/fukayo/.config/fukayo
    environment:
      - FUKAYO_USERNAME=toprak
      - FUKAYO_PASSWORD=blabblabla
    restart: unless-stopped
```

**Docker Logs**
```[18:0418/123109.796147:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
[19:0418/123142.911090:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[19:0418/123142.911196:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[19:0418/123143.238684:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[19:0418/123143.238729:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[19:0418/123143.238744:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[api] (web-server) closed
/home/fukayo/app/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:330
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Network.setUserAgentOverride): Target closed.
    at /home/fukayo/app/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:330:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (/home/fukayo/app/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:326:16)
    at next (/home/fukayo/app/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)
    at CDPSessionImpl.send (/home/fukayo/app/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:67:18)
    at Plugin.onPageCreated (/home/fukayo/app/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.js:182:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Plugin._onTargetCreated (/home/fukayo/app/resources/app/node_modules/puppeteer-extra-plugin/dist/index.cjs.js:496:21)

Node.js v18.12.1
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    17 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (14) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    17 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (14) - No such process
/usr/bin/xvfb-run: line 181:    17 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (14) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
/usr/bin/xvfb-run: line 181:    18 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/usr/bin/xvfb-run: line 186: kill: (15) - No such process
[18:0412/130806.295975:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[18:0412/130824.674694:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[18:0412/130830.062073:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[18:0412/130836.012247:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[18:0412/130843.388213:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[17:0412/130854.156374:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
(node:19) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 update-downloaded listeners added to [p]. Use emitter.setMaxListeners() to increase limit
[api] (web-server) closed
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
```

**Comment by ghost** [comment]
It closes itself when I read from komga and the manga did not load properly, also When I leave it idle, it shuts down by itself (I don't access fukayo at all for like 10 hours (estimated time) and when I try to access it in the morning, it won't access).

**Comment by ghost** [comment]
tried appimage without --no-sandbox flag, I had tried with --no-sandbox flag it had still closed itself, now without the that flag still same and here is the output.

```libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Update for version 0.19.28-beta is not available (latest version: 0.19.28-beta, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
Checking for update
Update for version 0.19.28-beta is not available (latest version: 0.19.28-beta, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
Checking for update
Update for version 0.19.28-beta is not available (latest version: 0.19.28-beta, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
Checking for update
Update for version 0.19.28-beta is not available (latest version: 0.19.28-beta, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
/tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:330
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Network.setUserAgentOverride): Target closed.
    at /tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:330:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (/tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:326:16)
    at next (/tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)
    at CDPSessionImpl.send (/tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:67:18)
    at Plugin.onPageCreated (/tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.js:182:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Plugin._onTargetCreated (/tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-extra-plugin/dist/index.cjs.js:496:21)

Node.js v18.12.1
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at new NodeError (node:internal/errors:393:5)
    at target.send (node:internal/child_process:740:16)
    at Timeout._onTimeout (/tmp/.mount_FukayoPZCINh/resources/app/packages/main/dist/index.cjs:1:8953)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
/tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:330
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Network.setUserAgentOverride): Target closed.
    at /tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:330:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (/tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:326:16)
    at next (/tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)
    at CDPSessionImpl.send (/tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:67:18)
    at Plugin.onPageCreated (/tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.js:182:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Plugin._onTargetCreated (/tmp/.mount_FukayoPZCINh/resources/app/node_modules/puppeteer-extra-plugin/dist/index.cjs.js:496:21)```

**Comment by JiPaix** [comment]
I can't replicate that issue but it seems related to puppeteer.
I updated puppeteer in `v0.20.0` let me know if it fixes the issue

**Comment by ghost** [comment]
@JiPaix no :(
```ProtocolError: Protocol error (Page.addScriptToEvaluateOnNewDocument): Target closed.
    at /home/fukayo/app/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:330:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (/home/fukayo/app/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:326:16)
    at next (/home/fukayo/app/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)
    at CDPSessionImpl.send (/home/fukayo/app/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:67:18)
    at CDPPage.evaluateOnNewDocument (/home/fukayo/app/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:660:66)
    at Object.evaluateOnNewDocument (/home/fukayo/app/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/_utils/withUtils.js:33:17)
    at Plugin.onPageCreated (/home/fukayo/app/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow/index.js:28:27)
    at Plugin._onTargetCreated (/home/fukayo/app/resources/app/node_modules/puppeteer-extra-plugin/dist/index.cjs.js:496:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
/home/fukayo/app/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:317
            return Promise.reject(new Error(`Protocol error (${method}): Session closed. Most likely the ${__classPrivateFieldGet(this, _CDPSessionImpl_targetType, "f")} has been closed.`));
                                  ^

Error: Protocol error (Network.setUserAgentOverride): Session closed. Most likely the page has been closed.
    at CDPSessionImpl.send (/home/fukayo/app/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:317:35)
    at next (/home/fukayo/app/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)
    at CDPSessionImpl.send (/home/fukayo/app/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:67:18)
    at Plugin.onPageCreated (/home/fukayo/app/resources/app/node_modules/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.js:182:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Plugin._onTargetCreated (/home/fukayo/app/resources/app/node_modules/puppeteer-extra-plugin/dist/index.cjs.js:496:21)

Node.js v18.12.1
```

**Comment by ghost** [comment]
I run it headless because I do not have enough ram on my laptop so I host it from another pc, so thats why I need to use headless, but if we got lazy loading again in future there wont need to fix it since I can use it from electron app

**Comment by ghost** [comment]
I write it since it could be relatable with this using electron app, when chapter could not be opened after retrying etc. update logo is spinning and I can't see anything when I click sidebar sections like everything disappears like it shows my library empty and I have to restart the app
